services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todolist_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5555"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todolist_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: mysecretkey
      JWT_EXPIRATION: 86400000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
volumes:
  db_data: