spring:
  application:
    name: Notification email service
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: earliest
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      database: 0

server:
  port: 6666

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, circuitbreakers
  health:
    circuitbreakers:
      enabled: true

resend:
  api-key: ${RESEND_API_KEY}