spring:
  application:
    name: Notification email service
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: notification-group
      auto-offset-reset: earliest
  data:
    redis:
      host: redis
      port: 6379
      database: 0

server:
  port: 6666

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, circuitbreakers
  health:
    circuitbreakers:
      enabled: true